package by.netcracker.chef.command;

public enum CommandName {
    GET_INDEX_PAGE,

    GET_CREATE_VEGETABLE_PAGE, CREATE_VEGETABLE, SHOW_VEGETABLE,
    GET_EDIT_VEGETABLE_PAGE, EDIT_VEGETABLE, DELETE_VEGETABLE,

    GET_CREATE_MENU_PAGE, CREATE_MENU, ADD_SALAD_TO_MENU,
    DELETE_SALAD_FROM_MENU, SHOW_MENU, GET_EDIT_MENU_PAGE,
    EDIT_MENU, DELETE_MENU,

    GET_CREATE_SALAD_PAGE, CREATE_SALAD, ADD_INGREDIENT_TO_SALAD,
    DELETE_INGREDIENT_FROM_SALAD, SHOW_SALAD, GET_EDIT_SALAD_PAGE,
    EDIT_SALAD, DELETE_SALAD
}
